var i = new ifc();
var x = new Date();
var y = new Date();
var t1 = new 53();
var t2 = new ''();
new Array();
(new Date()).toString();
var t3 = new Array();
var t4 = new Array();
var f = new q();
var t5 = new new Date()();
new String();