var simpleVar;
var anotherVar: any;
var varWithSimpleType: number;
var varWithArrayType: number[];
var varWithInitialValue: number;
var withComplicatedValue: { x: number; y: number; desc: string; };
var declaredVar;
var declareVar2;
var declaredVar;
var deckareVarWithType: number;
var arrayVar: string[];
var complicatedArrayVar: { x: number; y: string; }[];
var n1: { [s: string]: number; };
var c: { new?(): any; };
var d: { foo?(): { x: number; }; };
var d3: { foo(): { x: number; y: number; }; };
var d2: { foo(): { x: number; }; };
var n2: () => void;
var n4: { (): void; }[];
var d4: { foo(n: string,x: { x: number; y: number; }): { x: number; y: number; }; };

